{{
  config(
    materialized = 'table',
    )
}}

WITH Combined_Data AS (
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("AAPL_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("ABNB_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("ADBE_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("BA_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("DASH_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("GOOG_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("META_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("MSFT_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("NVDA_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("TSLA_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("PFE_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("MRNA_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("DE_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("FDX_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("DHLGY_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("DIS_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("NFLX_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("PEP_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("NSRGY_cleansed") }}
    UNION ALL
    SELECT POST_TITLE, POST_ID, POST_AUTHOR, POST_SCORE, COMMENT_AUTHOR, COMMENT, TICKER
    FROM {{ ref("LMT_cleansed") }}
)

SELECT *
FROM Combined_Data